name: C++ Cross-Platform Build

on: push

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, macos-10.15, windows-2019 ]
        mode: [ "Debug", "Release" ]
        include:
          - os: ubuntu-20.04
            pip-path: ~/.cache/pip
            exe-path: ./build/pengen
            cmake-args: -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10
          - os: macos-10.15
            pip-path: ~/Library/Caches/pip
            exe-path: ./build/pengen
            cmake-args: -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10  # See README.md
          - os: windows-2019
            pip-path: ~\AppData\Local\pip\Cache
            exe-path: ./build/pengen.exe

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: apt dependencies
        run: sudo apt install -y libtbb-dev  # libgtk2.0-dev
        if: startsWith(matrix.os, 'ubuntu')

      - name: Pip Cache
        uses: actions/cache@v2
        with:
          path: ${{ matrix.pip-path }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Pip Dependencies
        run: pip install -r requirements.txt

      - name: Conan Cache
        uses: actions/cache@v2
        with:
          path: ~/.conan
          key: ${{ runner.os }}-conan-${{ matrix.mode }}-v5-${{ hashFiles('**/conanfile.txt') }}
          restore-keys: |
            ${{ runner.os }}-conan-${{ matrix.mode }}-v5-

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -DPENGEN_WITH_PROFILER=ON ${{ matrix.cmake-args }} ..

      - name: Build
        working-directory: build
        run: cmake --build . --config ${{ matrix.mode }}

      - name: Generate Test Image
        run: ${{ matrix.exe-path }} --output ~/output.pgm 1024 1024

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: output-test-${{ runner.os }}-${{ matrix.mode }}.zip
          path: ~/output.pgm
          if-no-files-found: error
          retention-days: 14
