name: C++ Cross-Platform Build

on: push

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, macos-10.15, windows-2019 ]
        mode: [ "Debug", "Release" ]
        cppstd: [ 17, 20 ]
        include:
          - os: ubuntu-20.04
            cli-path: ./build/pengen
            lib-path: ./build/libpengen.a
          - os: macos-10.15
            cli-path: ./build/pengen
            lib-path: ./build/libpengen.a
          - os: windows-2019
            cli-path: ./build/pengen.exe
            lib-path: ./build/libpengen.lib
            pdb-path: ./build/*.pdb

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: apt dependencies
        run: sudo apt install -y libtbb-dev libgtk2.0-dev
        if: startsWith(matrix.os, 'ubuntu')

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_STANDARD=${{ matrix.cppstd }} \
                -DCMAKE_BUILD_TYPE=${{ matrix.mode }} \
                -DPENGEN_WITH_PROFILER=ON ..

      - name: Build
        working-directory: build
        run: cmake --build . --config ${{ matrix.mode }}

      - name: Generate Test Images
        run: |
          mkdir -p generated-images

          echo "Random:"
          ${{ matrix.cli-path }} --output ./generated-images/random.pgm 1024 1024
          echo "Ken Perlin:"
          ${{ matrix.cli-path }} --output ./generated-images/kenperlin.pgm --kenperlin 1024 1024

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-${{ matrix.mode }}-cpp${{ matrix.cppstd }}.zip
          path: |
            ./generated-images/*
            ${{ matrix.cli-path }}
            ${{ matrix.lib-path }}
            ${{ matrix.pdb-path }}
          if-no-files-found: warn
          retention-days: 14
